-- Hand-organized declarative schema (by domain). Edit freely — this file is the
-- canonical definition. Run `supabase db diff -f <name>` after editing to
-- produce the migration.
SET check_function_bodies = false;

-- Registry of countable things a reward can be earned against. The key is the
-- stable identifier a source reports progress under ('study.cards_reviewed');
-- a future source adds rows here without touching the counting machine.
CREATE TABLE public.reward_measures (
    key text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.reward_measures OWNER TO postgres;


-- Lifetime tally per (member, measure), stored as a counter that only ever goes
-- up via record_progress — never re-derived from source rows, so a deck reset
-- that deletes reviews cannot unwind milestones already crossed.
CREATE TABLE public.member_progress (
    member_id uuid NOT NULL,
    measure text NOT NULL,
    tally bigint DEFAULT 0 NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.member_progress OWNER TO postgres;


-- Catalogue of earnable milestones. `rewards` is the reward-list payload
-- apply_reward walks; `name_key` is an i18n key, never an English title, so the
-- catalogue carries no copy. Retunable data, not code.
CREATE TABLE public.milestones (
    id bigint NOT NULL,
    measure text NOT NULL,
    threshold bigint NOT NULL,
    rewards jsonb NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    name_key text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.milestones OWNER TO postgres;


ALTER TABLE public.milestones ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.milestones_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


-- The earned record — one row the first time a member crosses a milestone.
-- `seen_at` is null until the later reveal work marks it shown.
CREATE TABLE public.member_milestones (
    id bigint NOT NULL,
    member_id uuid NOT NULL,
    milestone_id bigint NOT NULL,
    earned_at timestamp with time zone DEFAULT now() NOT NULL,
    seen_at timestamp with time zone
);


ALTER TABLE public.member_milestones OWNER TO postgres;


ALTER TABLE public.member_milestones ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.member_milestones_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


-- Append-only paperclip movements. Balance is the SUM of entries
-- (member_paperclip_balance view), never a stored column — a member can edit
-- their own row, so a stored balance would be spoofable. apply_reward is the
-- sole writer. `member_milestone_id` is the earning event that produced the
-- entry, for provenance.
CREATE TABLE public.paperclip_ledger (
    id bigint NOT NULL,
    member_id uuid NOT NULL,
    amount bigint NOT NULL,
    member_milestone_id bigint,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.paperclip_ledger OWNER TO postgres;


ALTER TABLE public.paperclip_ledger ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.paperclip_ledger_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


-- Unlockable rewards a member has earned. Built for the generic core; no V1
-- milestone pays an unlockable yet, so nothing writes here today.
CREATE TABLE public.member_unlocks (
    id bigint NOT NULL,
    member_id uuid NOT NULL,
    unlock_key text NOT NULL,
    member_milestone_id bigint,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.member_unlocks OWNER TO postgres;


ALTER TABLE public.member_unlocks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.member_unlocks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


ALTER TABLE ONLY public.reward_measures
    ADD CONSTRAINT reward_measures_pkey PRIMARY KEY (key);


ALTER TABLE ONLY public.member_progress
    ADD CONSTRAINT member_progress_pkey PRIMARY KEY (member_id, measure);


ALTER TABLE ONLY public.milestones
    ADD CONSTRAINT milestones_pkey PRIMARY KEY (id);


ALTER TABLE ONLY public.milestones
    ADD CONSTRAINT milestones_measure_threshold_key UNIQUE (measure, threshold);


ALTER TABLE ONLY public.member_milestones
    ADD CONSTRAINT member_milestones_pkey PRIMARY KEY (id);


ALTER TABLE ONLY public.member_milestones
    ADD CONSTRAINT member_milestones_member_id_milestone_id_key UNIQUE (member_id, milestone_id);


ALTER TABLE ONLY public.paperclip_ledger
    ADD CONSTRAINT paperclip_ledger_pkey PRIMARY KEY (id);


ALTER TABLE ONLY public.member_unlocks
    ADD CONSTRAINT member_unlocks_pkey PRIMARY KEY (id);


ALTER TABLE ONLY public.member_unlocks
    ADD CONSTRAINT member_unlocks_member_id_unlock_key_key UNIQUE (member_id, unlock_key);


ALTER TABLE ONLY public.member_progress
    ADD CONSTRAINT member_progress_measure_fkey FOREIGN KEY (measure) REFERENCES public.reward_measures(key);


ALTER TABLE ONLY public.member_progress
    ADD CONSTRAINT member_progress_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.members(id) ON DELETE CASCADE;


ALTER TABLE ONLY public.milestones
    ADD CONSTRAINT milestones_measure_fkey FOREIGN KEY (measure) REFERENCES public.reward_measures(key);


ALTER TABLE ONLY public.member_milestones
    ADD CONSTRAINT member_milestones_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.members(id) ON DELETE CASCADE;


ALTER TABLE ONLY public.member_milestones
    ADD CONSTRAINT member_milestones_milestone_id_fkey FOREIGN KEY (milestone_id) REFERENCES public.milestones(id);


ALTER TABLE ONLY public.paperclip_ledger
    ADD CONSTRAINT paperclip_ledger_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.members(id) ON DELETE CASCADE;


ALTER TABLE ONLY public.paperclip_ledger
    ADD CONSTRAINT paperclip_ledger_member_milestone_id_fkey FOREIGN KEY (member_milestone_id) REFERENCES public.member_milestones(id) ON DELETE SET NULL;


ALTER TABLE ONLY public.member_unlocks
    ADD CONSTRAINT member_unlocks_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.members(id) ON DELETE CASCADE;


ALTER TABLE ONLY public.member_unlocks
    ADD CONSTRAINT member_unlocks_member_milestone_id_fkey FOREIGN KEY (member_milestone_id) REFERENCES public.member_milestones(id) ON DELETE SET NULL;


CREATE INDEX member_milestones_member_id_idx ON public.member_milestones USING btree (member_id);


CREATE INDEX paperclip_ledger_member_id_idx ON public.paperclip_ledger USING btree (member_id);


CREATE INDEX member_unlocks_member_id_idx ON public.member_unlocks USING btree (member_id);


-- Balance is the running sum of a member's ledger entries. security_invoker so
-- the paperclip_ledger SELECT policy runs per-caller — the view owner is
-- postgres, and without this it would read every member's rows.
CREATE VIEW public.member_paperclip_balance
    WITH (security_invoker = true) AS
    SELECT member_id,
           COALESCE(sum(amount), 0)::bigint AS balance
      FROM public.paperclip_ledger
     GROUP BY member_id;


ALTER VIEW public.member_paperclip_balance OWNER TO postgres;


ALTER TABLE public.reward_measures ENABLE ROW LEVEL SECURITY;


ALTER TABLE public.member_progress ENABLE ROW LEVEL SECURITY;


ALTER TABLE public.milestones ENABLE ROW LEVEL SECURITY;


ALTER TABLE public.member_milestones ENABLE ROW LEVEL SECURITY;


ALTER TABLE public.paperclip_ledger ENABLE ROW LEVEL SECURITY;


ALTER TABLE public.member_unlocks ENABLE ROW LEVEL SECURITY;


CREATE POLICY "measures readable by authenticated users" ON public.reward_measures FOR SELECT TO authenticated USING (true);


CREATE POLICY "active milestones readable by authenticated users" ON public.milestones FOR SELECT TO authenticated USING ((is_active = true));


CREATE POLICY "members can view their own progress" ON public.member_progress FOR SELECT TO authenticated USING ((( SELECT public.active_member_id() AS active_member_id) = member_id));


CREATE POLICY "members can view their own earned milestones" ON public.member_milestones FOR SELECT TO authenticated USING ((( SELECT public.active_member_id() AS active_member_id) = member_id));


CREATE POLICY "members can view their own ledger" ON public.paperclip_ledger FOR SELECT TO authenticated USING ((( SELECT public.active_member_id() AS active_member_id) = member_id));


CREATE POLICY "members can view their own unlocks" ON public.member_unlocks FOR SELECT TO authenticated USING ((( SELECT public.active_member_id() AS active_member_id) = member_id));


-- GRANT ALL to every client role mirrors public's default privileges, which
-- grant ALL on any new table anyway — RLS is the write boundary here, and no
-- table has an INSERT/UPDATE/DELETE policy, so nothing is client-writable
-- despite the broad grant. Declaring less than the defaults only drifts.
GRANT ALL ON TABLE public.reward_measures TO anon;
GRANT ALL ON TABLE public.reward_measures TO authenticated;
GRANT ALL ON TABLE public.reward_measures TO service_role;


GRANT ALL ON TABLE public.member_progress TO anon;
GRANT ALL ON TABLE public.member_progress TO authenticated;
GRANT ALL ON TABLE public.member_progress TO service_role;


GRANT ALL ON TABLE public.milestones TO anon;
GRANT ALL ON TABLE public.milestones TO authenticated;
GRANT ALL ON TABLE public.milestones TO service_role;


GRANT ALL ON SEQUENCE public.milestones_id_seq TO anon;
GRANT ALL ON SEQUENCE public.milestones_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.milestones_id_seq TO service_role;


GRANT ALL ON TABLE public.member_milestones TO anon;
GRANT ALL ON TABLE public.member_milestones TO authenticated;
GRANT ALL ON TABLE public.member_milestones TO service_role;


GRANT ALL ON SEQUENCE public.member_milestones_id_seq TO anon;
GRANT ALL ON SEQUENCE public.member_milestones_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.member_milestones_id_seq TO service_role;


GRANT ALL ON TABLE public.paperclip_ledger TO anon;
GRANT ALL ON TABLE public.paperclip_ledger TO authenticated;
GRANT ALL ON TABLE public.paperclip_ledger TO service_role;


GRANT ALL ON SEQUENCE public.paperclip_ledger_id_seq TO anon;
GRANT ALL ON SEQUENCE public.paperclip_ledger_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.paperclip_ledger_id_seq TO service_role;


GRANT ALL ON TABLE public.member_unlocks TO anon;
GRANT ALL ON TABLE public.member_unlocks TO authenticated;
GRANT ALL ON TABLE public.member_unlocks TO service_role;


GRANT ALL ON SEQUENCE public.member_unlocks_id_seq TO anon;
GRANT ALL ON SEQUENCE public.member_unlocks_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.member_unlocks_id_seq TO service_role;


GRANT ALL ON TABLE public.member_paperclip_balance TO anon;
GRANT ALL ON TABLE public.member_paperclip_balance TO authenticated;
GRANT ALL ON TABLE public.member_paperclip_balance TO service_role;
