-- Hand-organized declarative schema (by domain). Edit freely — this file is the
-- canonical definition. Run `supabase db diff -f <name>` after editing to
-- produce the migration.
SET check_function_bodies = false;

-- Registry of countable things a reward can be earned against. The key is the
-- stable identifier a source reports progress under ('study.cards_reviewed');
-- a future source adds rows here without touching the counting machine.
CREATE TABLE public.reward_metrics (
    key text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.reward_metrics OWNER TO postgres;


-- Lifetime tally per (member, metric), stored as a counter that only ever goes
-- up via record_progress — never re-derived from source rows, so a deck reset
-- that deletes reviews cannot unwind milestones already crossed →[K:reward-tally-survives-reset].
CREATE TABLE public.member_tallies (
    member_id uuid NOT NULL,
    metric text NOT NULL,
    tally bigint DEFAULT 0 NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.member_tallies OWNER TO postgres;


-- Catalogue of earnable milestones. `rewards` is the reward-list payload
-- apply_reward walks; `name_key` is an i18n key, never an English title, so the
-- catalogue carries no copy. Retunable data, not code.
CREATE TABLE public.reward_milestones (
    id bigint NOT NULL,
    metric text NOT NULL,
    threshold bigint NOT NULL,
    rewards jsonb NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    name_key text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.reward_milestones OWNER TO postgres;


ALTER TABLE public.reward_milestones ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reward_milestones_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


-- The earned record — one row the first time a member crosses a milestone.
-- `seen_at` is null until the later reveal work marks it shown.
CREATE TABLE public.member_rewards (
    id bigint NOT NULL,
    member_id uuid NOT NULL,
    reward_milestone_id bigint NOT NULL,
    earned_at timestamp with time zone DEFAULT now() NOT NULL,
    seen_at timestamp with time zone
);


ALTER TABLE public.member_rewards OWNER TO postgres;


ALTER TABLE public.member_rewards ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.member_rewards_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


-- Append-only paperclip movements. Balance is the SUM of entries
-- (paperclip_balance view), never a stored column — a member can edit
-- their own row, so a stored balance would be spoofable. apply_reward is the
-- sole writer. `member_reward_id` is the earning event that produced the
-- entry, for provenance.
CREATE TABLE public.paperclip_ledger (
    id bigint NOT NULL,
    member_id uuid NOT NULL,
    amount bigint NOT NULL,
    member_reward_id bigint,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.paperclip_ledger OWNER TO postgres;


ALTER TABLE public.paperclip_ledger ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.paperclip_ledger_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


-- Unlockable rewards a member has earned. Built for the generic core; no V1
-- milestone pays an unlockable yet, so nothing writes here today.
CREATE TABLE public.member_inventory (
    id bigint NOT NULL,
    member_id uuid NOT NULL,
    unlock_key text NOT NULL,
    member_reward_id bigint,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.member_inventory OWNER TO postgres;


ALTER TABLE public.member_inventory ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.member_inventory_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


ALTER TABLE ONLY public.reward_metrics
    ADD CONSTRAINT reward_metrics_pkey PRIMARY KEY (key);


ALTER TABLE ONLY public.member_tallies
    ADD CONSTRAINT member_tallies_pkey PRIMARY KEY (member_id, metric);


ALTER TABLE ONLY public.reward_milestones
    ADD CONSTRAINT reward_milestones_pkey PRIMARY KEY (id);


ALTER TABLE ONLY public.reward_milestones
    ADD CONSTRAINT reward_milestones_metric_threshold_key UNIQUE (metric, threshold);


ALTER TABLE ONLY public.member_rewards
    ADD CONSTRAINT member_rewards_pkey PRIMARY KEY (id);


ALTER TABLE ONLY public.member_rewards
    ADD CONSTRAINT member_rewards_member_id_reward_milestone_id_key UNIQUE (member_id, reward_milestone_id);


ALTER TABLE ONLY public.paperclip_ledger
    ADD CONSTRAINT paperclip_ledger_pkey PRIMARY KEY (id);


ALTER TABLE ONLY public.member_inventory
    ADD CONSTRAINT member_inventory_pkey PRIMARY KEY (id);


ALTER TABLE ONLY public.member_inventory
    ADD CONSTRAINT member_inventory_member_id_unlock_key_key UNIQUE (member_id, unlock_key);


ALTER TABLE ONLY public.member_tallies
    ADD CONSTRAINT member_tallies_metric_fkey FOREIGN KEY (metric) REFERENCES public.reward_metrics(key);


ALTER TABLE ONLY public.member_tallies
    ADD CONSTRAINT member_tallies_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.members(id) ON DELETE CASCADE;


ALTER TABLE ONLY public.reward_milestones
    ADD CONSTRAINT reward_milestones_metric_fkey FOREIGN KEY (metric) REFERENCES public.reward_metrics(key);


ALTER TABLE ONLY public.member_rewards
    ADD CONSTRAINT member_rewards_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.members(id) ON DELETE CASCADE;


ALTER TABLE ONLY public.member_rewards
    ADD CONSTRAINT member_rewards_reward_milestone_id_fkey FOREIGN KEY (reward_milestone_id) REFERENCES public.reward_milestones(id);


ALTER TABLE ONLY public.paperclip_ledger
    ADD CONSTRAINT paperclip_ledger_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.members(id) ON DELETE CASCADE;


ALTER TABLE ONLY public.paperclip_ledger
    ADD CONSTRAINT paperclip_ledger_member_reward_id_fkey FOREIGN KEY (member_reward_id) REFERENCES public.member_rewards(id) ON DELETE SET NULL;


ALTER TABLE ONLY public.member_inventory
    ADD CONSTRAINT member_inventory_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.members(id) ON DELETE CASCADE;


ALTER TABLE ONLY public.member_inventory
    ADD CONSTRAINT member_inventory_member_reward_id_fkey FOREIGN KEY (member_reward_id) REFERENCES public.member_rewards(id) ON DELETE SET NULL;


CREATE INDEX member_rewards_member_id_idx ON public.member_rewards USING btree (member_id);


CREATE INDEX paperclip_ledger_member_id_idx ON public.paperclip_ledger USING btree (member_id);


CREATE INDEX member_inventory_member_id_idx ON public.member_inventory USING btree (member_id);


-- Balance is the running sum of a member's ledger entries. security_invoker so
-- the paperclip_ledger SELECT policy runs per-caller — the view owner is
-- postgres, and without this it would read every member's rows.
CREATE VIEW public.paperclip_balance
    WITH (security_invoker = true) AS
    SELECT member_id,
           COALESCE(sum(amount), 0)::bigint AS balance
      FROM public.paperclip_ledger
     GROUP BY member_id;


ALTER VIEW public.paperclip_balance OWNER TO postgres;


ALTER TABLE public.reward_metrics ENABLE ROW LEVEL SECURITY;


ALTER TABLE public.member_tallies ENABLE ROW LEVEL SECURITY;


ALTER TABLE public.reward_milestones ENABLE ROW LEVEL SECURITY;


ALTER TABLE public.member_rewards ENABLE ROW LEVEL SECURITY;


ALTER TABLE public.paperclip_ledger ENABLE ROW LEVEL SECURITY;


ALTER TABLE public.member_inventory ENABLE ROW LEVEL SECURITY;


CREATE POLICY "metrics readable by authenticated users" ON public.reward_metrics FOR SELECT TO authenticated USING (true);


CREATE POLICY "active milestones readable by authenticated users" ON public.reward_milestones FOR SELECT TO authenticated USING ((is_active = true));


CREATE POLICY "members can view their own tallies" ON public.member_tallies FOR SELECT TO authenticated USING ((( SELECT public.active_member_id() AS active_member_id) = member_id));


CREATE POLICY "members can view their own earned rewards" ON public.member_rewards FOR SELECT TO authenticated USING ((( SELECT public.active_member_id() AS active_member_id) = member_id));


CREATE POLICY "members can view their own ledger" ON public.paperclip_ledger FOR SELECT TO authenticated USING ((( SELECT public.active_member_id() AS active_member_id) = member_id));


CREATE POLICY "members can view their own inventory" ON public.member_inventory FOR SELECT TO authenticated USING ((( SELECT public.active_member_id() AS active_member_id) = member_id));


-- GRANT ALL to every client role mirrors public's default privileges, which
-- grant ALL on any new table anyway — RLS is the write boundary here, and no
-- table has an INSERT/UPDATE/DELETE policy, so nothing is client-writable
-- despite the broad grant. Declaring less than the defaults only drifts.
GRANT ALL ON TABLE public.reward_metrics TO anon;
GRANT ALL ON TABLE public.reward_metrics TO authenticated;
GRANT ALL ON TABLE public.reward_metrics TO service_role;


GRANT ALL ON TABLE public.member_tallies TO anon;
GRANT ALL ON TABLE public.member_tallies TO authenticated;
GRANT ALL ON TABLE public.member_tallies TO service_role;


GRANT ALL ON TABLE public.reward_milestones TO anon;
GRANT ALL ON TABLE public.reward_milestones TO authenticated;
GRANT ALL ON TABLE public.reward_milestones TO service_role;


GRANT ALL ON SEQUENCE public.reward_milestones_id_seq TO anon;
GRANT ALL ON SEQUENCE public.reward_milestones_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.reward_milestones_id_seq TO service_role;


GRANT ALL ON TABLE public.member_rewards TO anon;
GRANT ALL ON TABLE public.member_rewards TO authenticated;
GRANT ALL ON TABLE public.member_rewards TO service_role;


GRANT ALL ON SEQUENCE public.member_rewards_id_seq TO anon;
GRANT ALL ON SEQUENCE public.member_rewards_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.member_rewards_id_seq TO service_role;


GRANT ALL ON TABLE public.paperclip_ledger TO anon;
GRANT ALL ON TABLE public.paperclip_ledger TO authenticated;
GRANT ALL ON TABLE public.paperclip_ledger TO service_role;


GRANT ALL ON SEQUENCE public.paperclip_ledger_id_seq TO anon;
GRANT ALL ON SEQUENCE public.paperclip_ledger_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.paperclip_ledger_id_seq TO service_role;


GRANT ALL ON TABLE public.member_inventory TO anon;
GRANT ALL ON TABLE public.member_inventory TO authenticated;
GRANT ALL ON TABLE public.member_inventory TO service_role;


GRANT ALL ON SEQUENCE public.member_inventory_id_seq TO anon;
GRANT ALL ON SEQUENCE public.member_inventory_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.member_inventory_id_seq TO service_role;


GRANT ALL ON TABLE public.paperclip_balance TO anon;
GRANT ALL ON TABLE public.paperclip_balance TO authenticated;
GRANT ALL ON TABLE public.paperclip_balance TO service_role;
