-- knowledge: reward_metrics, member_tallies, reward_milestones, member_rewards, paperclip_ledger, member_inventory, paperclip_balance, record_progress, apply_reward — unrecorded

  create table "public"."member_rewards" (
    "id" bigint generated by default as identity not null,
    "member_id" uuid not null,
    "reward_milestone_id" bigint not null,
    "earned_at" timestamp with time zone not null default now(),
    "seen_at" timestamp with time zone
      );


alter table "public"."member_rewards" enable row level security;


  create table "public"."member_tallies" (
    "member_id" uuid not null,
    "metric" text not null,
    "tally" bigint not null default 0,
    "updated_at" timestamp with time zone not null default now()
      );


alter table "public"."member_tallies" enable row level security;


  create table "public"."member_inventory" (
    "id" bigint generated by default as identity not null,
    "member_id" uuid not null,
    "unlock_key" text not null,
    "member_reward_id" bigint,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."member_inventory" enable row level security;


  create table "public"."reward_milestones" (
    "id" bigint generated by default as identity not null,
    "metric" text not null,
    "threshold" bigint not null,
    "rewards" jsonb not null,
    "is_active" boolean not null default true,
    "name_key" text not null,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."reward_milestones" enable row level security;


  create table "public"."paperclip_ledger" (
    "id" bigint generated by default as identity not null,
    "member_id" uuid not null,
    "amount" bigint not null,
    "member_reward_id" bigint,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."paperclip_ledger" enable row level security;


  create table "public"."reward_metrics" (
    "key" text not null,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."reward_metrics" enable row level security;

CREATE INDEX member_rewards_member_id_idx ON public.member_rewards USING btree (member_id);

CREATE UNIQUE INDEX member_rewards_member_id_reward_milestone_id_key ON public.member_rewards USING btree (member_id, reward_milestone_id);

CREATE UNIQUE INDEX member_rewards_pkey ON public.member_rewards USING btree (id);

CREATE UNIQUE INDEX member_tallies_pkey ON public.member_tallies USING btree (member_id, metric);

CREATE INDEX member_inventory_member_id_idx ON public.member_inventory USING btree (member_id);

CREATE UNIQUE INDEX member_inventory_member_id_unlock_key_key ON public.member_inventory USING btree (member_id, unlock_key);

CREATE UNIQUE INDEX member_inventory_pkey ON public.member_inventory USING btree (id);

CREATE UNIQUE INDEX reward_milestones_metric_threshold_key ON public.reward_milestones USING btree (metric, threshold);

CREATE UNIQUE INDEX reward_milestones_pkey ON public.reward_milestones USING btree (id);

CREATE INDEX paperclip_ledger_member_id_idx ON public.paperclip_ledger USING btree (member_id);

CREATE UNIQUE INDEX paperclip_ledger_pkey ON public.paperclip_ledger USING btree (id);

CREATE UNIQUE INDEX reward_metrics_pkey ON public.reward_metrics USING btree (key);

alter table "public"."member_rewards" add constraint "member_rewards_pkey" PRIMARY KEY using index "member_rewards_pkey";

alter table "public"."member_tallies" add constraint "member_tallies_pkey" PRIMARY KEY using index "member_tallies_pkey";

alter table "public"."member_inventory" add constraint "member_inventory_pkey" PRIMARY KEY using index "member_inventory_pkey";

alter table "public"."reward_milestones" add constraint "reward_milestones_pkey" PRIMARY KEY using index "reward_milestones_pkey";

alter table "public"."paperclip_ledger" add constraint "paperclip_ledger_pkey" PRIMARY KEY using index "paperclip_ledger_pkey";

alter table "public"."reward_metrics" add constraint "reward_metrics_pkey" PRIMARY KEY using index "reward_metrics_pkey";

alter table "public"."member_rewards" add constraint "member_rewards_member_id_fkey" FOREIGN KEY (member_id) REFERENCES public.members(id) ON DELETE CASCADE not valid;

alter table "public"."member_rewards" validate constraint "member_rewards_member_id_fkey";

alter table "public"."member_rewards" add constraint "member_rewards_member_id_reward_milestone_id_key" UNIQUE using index "member_rewards_member_id_reward_milestone_id_key";

alter table "public"."member_rewards" add constraint "member_rewards_reward_milestone_id_fkey" FOREIGN KEY (reward_milestone_id) REFERENCES public.reward_milestones(id) not valid;

alter table "public"."member_rewards" validate constraint "member_rewards_reward_milestone_id_fkey";

alter table "public"."member_tallies" add constraint "member_tallies_metric_fkey" FOREIGN KEY (metric) REFERENCES public.reward_metrics(key) not valid;

alter table "public"."member_tallies" validate constraint "member_tallies_metric_fkey";

alter table "public"."member_tallies" add constraint "member_tallies_member_id_fkey" FOREIGN KEY (member_id) REFERENCES public.members(id) ON DELETE CASCADE not valid;

alter table "public"."member_tallies" validate constraint "member_tallies_member_id_fkey";

alter table "public"."member_inventory" add constraint "member_inventory_member_id_fkey" FOREIGN KEY (member_id) REFERENCES public.members(id) ON DELETE CASCADE not valid;

alter table "public"."member_inventory" validate constraint "member_inventory_member_id_fkey";

alter table "public"."member_inventory" add constraint "member_inventory_member_id_unlock_key_key" UNIQUE using index "member_inventory_member_id_unlock_key_key";

alter table "public"."member_inventory" add constraint "member_inventory_member_reward_id_fkey" FOREIGN KEY (member_reward_id) REFERENCES public.member_rewards(id) ON DELETE SET NULL not valid;

alter table "public"."member_inventory" validate constraint "member_inventory_member_reward_id_fkey";

alter table "public"."reward_milestones" add constraint "reward_milestones_metric_fkey" FOREIGN KEY (metric) REFERENCES public.reward_metrics(key) not valid;

alter table "public"."reward_milestones" validate constraint "reward_milestones_metric_fkey";

alter table "public"."reward_milestones" add constraint "reward_milestones_metric_threshold_key" UNIQUE using index "reward_milestones_metric_threshold_key";

alter table "public"."paperclip_ledger" add constraint "paperclip_ledger_member_id_fkey" FOREIGN KEY (member_id) REFERENCES public.members(id) ON DELETE CASCADE not valid;

alter table "public"."paperclip_ledger" validate constraint "paperclip_ledger_member_id_fkey";

alter table "public"."paperclip_ledger" add constraint "paperclip_ledger_member_reward_id_fkey" FOREIGN KEY (member_reward_id) REFERENCES public.member_rewards(id) ON DELETE SET NULL not valid;

alter table "public"."paperclip_ledger" validate constraint "paperclip_ledger_member_reward_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.apply_reward(p_member uuid, p_rewards jsonb, p_member_reward bigint)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  v_reward jsonb;
  v_kind   text;
BEGIN
  -- Walk the reward list and dispatch on kind. Each branch resolves its payload
  -- entry as a spec and persists the concrete outcome, so a future randomized
  -- reward computes its value here without any change upstream in record_progress
  -- — and editing a milestone's reward payload later never touches what an
  -- already-earned member was actually paid →[K:reward-payout-is-resolved-not-spec].
  FOR v_reward IN SELECT * FROM jsonb_array_elements(p_rewards)
  LOOP
    v_kind := v_reward ->> 'kind';

    IF v_kind = 'paperclips' THEN
      -- The ledger is the only place a balance lives; this insert is the sole
      -- writer. The resolved amount is what gets stored, never the spec.
      INSERT INTO public.paperclip_ledger (member_id, amount, member_reward_id)
      VALUES (p_member, (v_reward ->> 'amount')::bigint, p_member_reward);
    ELSE
      RAISE EXCEPTION 'Unknown reward kind: %', v_kind;
    END IF;
  END LOOP;
END;
$function$
;

-- security_invoker restored by hand: db diff omits view reloptions, so the
-- generated create-or-replace would drop it and the view would read every
-- member's ledger rows instead of running the SELECT policy per-caller.
create or replace view "public"."paperclip_balance" with (security_invoker=true) as  SELECT paperclip_ledger.member_id,
    (COALESCE(sum(paperclip_ledger.amount), (0)::numeric))::bigint AS balance
   FROM public.paperclip_ledger
  GROUP BY paperclip_ledger.member_id;


CREATE OR REPLACE FUNCTION public.record_progress(p_member uuid, p_metric text, p_delta bigint)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  v_old bigint;
  v_new bigint;
  v_ms  public.reward_milestones%ROWTYPE;
  v_mm_id bigint;
BEGIN
  -- Ensure the tally row exists, then lock it for the rest of the transaction so
  -- two concurrent sources counting the same metric can't both read the same
  -- `old` and pay a milestone twice.
  INSERT INTO public.member_tallies (member_id, metric, tally)
  VALUES (p_member, p_metric, 0)
  ON CONFLICT (member_id, metric) DO NOTHING;

  SELECT tally INTO v_old
    FROM public.member_tallies
   WHERE member_id = p_member AND metric = p_metric
     FOR UPDATE;

  v_new := v_old + p_delta;

  UPDATE public.member_tallies
     SET tally = v_new, updated_at = now()
   WHERE member_id = p_member AND metric = p_metric;

  -- Milestones whose threshold falls in (old, new] and that this member hasn't
  -- already earned. The half-open interval is the one-shot guard: a later call
  -- that pushes the tally further never re-crosses a threshold already below old.
  FOR v_ms IN
    SELECT m.*
      FROM public.reward_milestones m
     WHERE m.metric = p_metric
       AND m.is_active
       AND m.threshold > v_old
       AND m.threshold <= v_new
       AND NOT EXISTS (
         SELECT 1 FROM public.member_rewards mm
          WHERE mm.member_id = p_member AND mm.reward_milestone_id = m.id
       )
     ORDER BY m.threshold
  LOOP
    -- The unique (member_id, reward_milestone_id) makes the insert the durable
    -- one-shot guard even under a race; DO NOTHING + null RETURNING means a
    -- concurrent winner already paid, so this call skips apply_reward.
    INSERT INTO public.member_rewards (member_id, reward_milestone_id)
    VALUES (p_member, v_ms.id)
    ON CONFLICT (member_id, reward_milestone_id) DO NOTHING
    RETURNING id INTO v_mm_id;

    IF v_mm_id IS NOT NULL THEN
      PERFORM public.apply_reward(p_member, v_ms.rewards, v_mm_id);
    END IF;
  END LOOP;
END;
$function$
;

grant references on table "public"."member_rewards" to "anon";

grant trigger on table "public"."member_rewards" to "anon";

grant truncate on table "public"."member_rewards" to "anon";

grant references on table "public"."member_rewards" to "authenticated";

grant select on table "public"."member_rewards" to "authenticated";

grant trigger on table "public"."member_rewards" to "authenticated";

grant truncate on table "public"."member_rewards" to "authenticated";

grant delete on table "public"."member_rewards" to "service_role";

grant insert on table "public"."member_rewards" to "service_role";

grant references on table "public"."member_rewards" to "service_role";

grant select on table "public"."member_rewards" to "service_role";

grant trigger on table "public"."member_rewards" to "service_role";

grant truncate on table "public"."member_rewards" to "service_role";

grant update on table "public"."member_rewards" to "service_role";

grant references on table "public"."member_tallies" to "anon";

grant trigger on table "public"."member_tallies" to "anon";

grant truncate on table "public"."member_tallies" to "anon";

grant references on table "public"."member_tallies" to "authenticated";

grant select on table "public"."member_tallies" to "authenticated";

grant trigger on table "public"."member_tallies" to "authenticated";

grant truncate on table "public"."member_tallies" to "authenticated";

grant delete on table "public"."member_tallies" to "service_role";

grant insert on table "public"."member_tallies" to "service_role";

grant references on table "public"."member_tallies" to "service_role";

grant select on table "public"."member_tallies" to "service_role";

grant trigger on table "public"."member_tallies" to "service_role";

grant truncate on table "public"."member_tallies" to "service_role";

grant update on table "public"."member_tallies" to "service_role";

grant references on table "public"."member_inventory" to "anon";

grant trigger on table "public"."member_inventory" to "anon";

grant truncate on table "public"."member_inventory" to "anon";

grant references on table "public"."member_inventory" to "authenticated";

grant select on table "public"."member_inventory" to "authenticated";

grant trigger on table "public"."member_inventory" to "authenticated";

grant truncate on table "public"."member_inventory" to "authenticated";

grant delete on table "public"."member_inventory" to "service_role";

grant insert on table "public"."member_inventory" to "service_role";

grant references on table "public"."member_inventory" to "service_role";

grant select on table "public"."member_inventory" to "service_role";

grant trigger on table "public"."member_inventory" to "service_role";

grant truncate on table "public"."member_inventory" to "service_role";

grant update on table "public"."member_inventory" to "service_role";

grant references on table "public"."reward_milestones" to "anon";

grant trigger on table "public"."reward_milestones" to "anon";

grant truncate on table "public"."reward_milestones" to "anon";

grant references on table "public"."reward_milestones" to "authenticated";

grant select on table "public"."reward_milestones" to "authenticated";

grant trigger on table "public"."reward_milestones" to "authenticated";

grant truncate on table "public"."reward_milestones" to "authenticated";

grant delete on table "public"."reward_milestones" to "service_role";

grant insert on table "public"."reward_milestones" to "service_role";

grant references on table "public"."reward_milestones" to "service_role";

grant select on table "public"."reward_milestones" to "service_role";

grant trigger on table "public"."reward_milestones" to "service_role";

grant truncate on table "public"."reward_milestones" to "service_role";

grant update on table "public"."reward_milestones" to "service_role";

grant references on table "public"."paperclip_ledger" to "anon";

grant trigger on table "public"."paperclip_ledger" to "anon";

grant truncate on table "public"."paperclip_ledger" to "anon";

grant references on table "public"."paperclip_ledger" to "authenticated";

grant select on table "public"."paperclip_ledger" to "authenticated";

grant trigger on table "public"."paperclip_ledger" to "authenticated";

grant truncate on table "public"."paperclip_ledger" to "authenticated";

grant delete on table "public"."paperclip_ledger" to "service_role";

grant insert on table "public"."paperclip_ledger" to "service_role";

grant references on table "public"."paperclip_ledger" to "service_role";

grant select on table "public"."paperclip_ledger" to "service_role";

grant trigger on table "public"."paperclip_ledger" to "service_role";

grant truncate on table "public"."paperclip_ledger" to "service_role";

grant update on table "public"."paperclip_ledger" to "service_role";

grant references on table "public"."reward_metrics" to "anon";

grant trigger on table "public"."reward_metrics" to "anon";

grant truncate on table "public"."reward_metrics" to "anon";

grant references on table "public"."reward_metrics" to "authenticated";

grant select on table "public"."reward_metrics" to "authenticated";

grant trigger on table "public"."reward_metrics" to "authenticated";

grant truncate on table "public"."reward_metrics" to "authenticated";

grant delete on table "public"."reward_metrics" to "service_role";

grant insert on table "public"."reward_metrics" to "service_role";

grant references on table "public"."reward_metrics" to "service_role";

grant select on table "public"."reward_metrics" to "service_role";

grant trigger on table "public"."reward_metrics" to "service_role";

grant truncate on table "public"."reward_metrics" to "service_role";

grant update on table "public"."reward_metrics" to "service_role";


  create policy "members can view their own earned rewards"
  on "public"."member_rewards"
  as permissive
  for select
  to authenticated
using ((( SELECT public.active_member_id() AS active_member_id) = member_id));



  create policy "members can view their own tallies"
  on "public"."member_tallies"
  as permissive
  for select
  to authenticated
using ((( SELECT public.active_member_id() AS active_member_id) = member_id));



  create policy "members can view their own inventory"
  on "public"."member_inventory"
  as permissive
  for select
  to authenticated
using ((( SELECT public.active_member_id() AS active_member_id) = member_id));



  create policy "active milestones readable by authenticated users"
  on "public"."reward_milestones"
  as permissive
  for select
  to authenticated
using ((is_active = true));



  create policy "members can view their own ledger"
  on "public"."paperclip_ledger"
  as permissive
  for select
  to authenticated
using ((( SELECT public.active_member_id() AS active_member_id) = member_id));



  create policy "metrics readable by authenticated users"
  on "public"."reward_metrics"
  as permissive
  for select
  to authenticated
using (true);


-- Hand-written: db diff emits no function grants, so without these the two
-- internal definer functions land EXECUTE-able by PUBLIC (anon included). They
-- are reusable seams called only from other definer functions, never a client.
revoke all on function public.apply_reward(p_member uuid, p_rewards jsonb, p_member_reward bigint) from public;
revoke all on function public.apply_reward(p_member uuid, p_rewards jsonb, p_member_reward bigint) from anon;
revoke all on function public.apply_reward(p_member uuid, p_rewards jsonb, p_member_reward bigint) from authenticated;
grant all on function public.apply_reward(p_member uuid, p_rewards jsonb, p_member_reward bigint) to service_role;

revoke all on function public.record_progress(p_member uuid, p_metric text, p_delta bigint) from public;
revoke all on function public.record_progress(p_member uuid, p_metric text, p_delta bigint) from anon;
revoke all on function public.record_progress(p_member uuid, p_metric text, p_delta bigint) from authenticated;
grant all on function public.record_progress(p_member uuid, p_metric text, p_delta bigint) to service_role;
