-- knowledge: reward_measures, member_progress, milestones, member_milestones, paperclip_ledger, member_unlocks, member_paperclip_balance, record_progress, apply_reward — unrecorded

  create table "public"."member_milestones" (
    "id" bigint generated by default as identity not null,
    "member_id" uuid not null,
    "milestone_id" bigint not null,
    "earned_at" timestamp with time zone not null default now(),
    "seen_at" timestamp with time zone
      );


alter table "public"."member_milestones" enable row level security;


  create table "public"."member_progress" (
    "member_id" uuid not null,
    "measure" text not null,
    "tally" bigint not null default 0,
    "updated_at" timestamp with time zone not null default now()
      );


alter table "public"."member_progress" enable row level security;


  create table "public"."member_unlocks" (
    "id" bigint generated by default as identity not null,
    "member_id" uuid not null,
    "unlock_key" text not null,
    "member_milestone_id" bigint,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."member_unlocks" enable row level security;


  create table "public"."milestones" (
    "id" bigint generated by default as identity not null,
    "measure" text not null,
    "threshold" bigint not null,
    "rewards" jsonb not null,
    "is_active" boolean not null default true,
    "name_key" text not null,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."milestones" enable row level security;


  create table "public"."paperclip_ledger" (
    "id" bigint generated by default as identity not null,
    "member_id" uuid not null,
    "amount" bigint not null,
    "member_milestone_id" bigint,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."paperclip_ledger" enable row level security;


  create table "public"."reward_measures" (
    "key" text not null,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."reward_measures" enable row level security;

CREATE INDEX member_milestones_member_id_idx ON public.member_milestones USING btree (member_id);

CREATE UNIQUE INDEX member_milestones_member_id_milestone_id_key ON public.member_milestones USING btree (member_id, milestone_id);

CREATE UNIQUE INDEX member_milestones_pkey ON public.member_milestones USING btree (id);

CREATE UNIQUE INDEX member_progress_pkey ON public.member_progress USING btree (member_id, measure);

CREATE INDEX member_unlocks_member_id_idx ON public.member_unlocks USING btree (member_id);

CREATE UNIQUE INDEX member_unlocks_member_id_unlock_key_key ON public.member_unlocks USING btree (member_id, unlock_key);

CREATE UNIQUE INDEX member_unlocks_pkey ON public.member_unlocks USING btree (id);

CREATE UNIQUE INDEX milestones_measure_threshold_key ON public.milestones USING btree (measure, threshold);

CREATE UNIQUE INDEX milestones_pkey ON public.milestones USING btree (id);

CREATE INDEX paperclip_ledger_member_id_idx ON public.paperclip_ledger USING btree (member_id);

CREATE UNIQUE INDEX paperclip_ledger_pkey ON public.paperclip_ledger USING btree (id);

CREATE UNIQUE INDEX reward_measures_pkey ON public.reward_measures USING btree (key);

alter table "public"."member_milestones" add constraint "member_milestones_pkey" PRIMARY KEY using index "member_milestones_pkey";

alter table "public"."member_progress" add constraint "member_progress_pkey" PRIMARY KEY using index "member_progress_pkey";

alter table "public"."member_unlocks" add constraint "member_unlocks_pkey" PRIMARY KEY using index "member_unlocks_pkey";

alter table "public"."milestones" add constraint "milestones_pkey" PRIMARY KEY using index "milestones_pkey";

alter table "public"."paperclip_ledger" add constraint "paperclip_ledger_pkey" PRIMARY KEY using index "paperclip_ledger_pkey";

alter table "public"."reward_measures" add constraint "reward_measures_pkey" PRIMARY KEY using index "reward_measures_pkey";

alter table "public"."member_milestones" add constraint "member_milestones_member_id_fkey" FOREIGN KEY (member_id) REFERENCES public.members(id) ON DELETE CASCADE not valid;

alter table "public"."member_milestones" validate constraint "member_milestones_member_id_fkey";

alter table "public"."member_milestones" add constraint "member_milestones_member_id_milestone_id_key" UNIQUE using index "member_milestones_member_id_milestone_id_key";

alter table "public"."member_milestones" add constraint "member_milestones_milestone_id_fkey" FOREIGN KEY (milestone_id) REFERENCES public.milestones(id) not valid;

alter table "public"."member_milestones" validate constraint "member_milestones_milestone_id_fkey";

alter table "public"."member_progress" add constraint "member_progress_measure_fkey" FOREIGN KEY (measure) REFERENCES public.reward_measures(key) not valid;

alter table "public"."member_progress" validate constraint "member_progress_measure_fkey";

alter table "public"."member_progress" add constraint "member_progress_member_id_fkey" FOREIGN KEY (member_id) REFERENCES public.members(id) ON DELETE CASCADE not valid;

alter table "public"."member_progress" validate constraint "member_progress_member_id_fkey";

alter table "public"."member_unlocks" add constraint "member_unlocks_member_id_fkey" FOREIGN KEY (member_id) REFERENCES public.members(id) ON DELETE CASCADE not valid;

alter table "public"."member_unlocks" validate constraint "member_unlocks_member_id_fkey";

alter table "public"."member_unlocks" add constraint "member_unlocks_member_id_unlock_key_key" UNIQUE using index "member_unlocks_member_id_unlock_key_key";

alter table "public"."member_unlocks" add constraint "member_unlocks_member_milestone_id_fkey" FOREIGN KEY (member_milestone_id) REFERENCES public.member_milestones(id) ON DELETE SET NULL not valid;

alter table "public"."member_unlocks" validate constraint "member_unlocks_member_milestone_id_fkey";

alter table "public"."milestones" add constraint "milestones_measure_fkey" FOREIGN KEY (measure) REFERENCES public.reward_measures(key) not valid;

alter table "public"."milestones" validate constraint "milestones_measure_fkey";

alter table "public"."milestones" add constraint "milestones_measure_threshold_key" UNIQUE using index "milestones_measure_threshold_key";

alter table "public"."paperclip_ledger" add constraint "paperclip_ledger_member_id_fkey" FOREIGN KEY (member_id) REFERENCES public.members(id) ON DELETE CASCADE not valid;

alter table "public"."paperclip_ledger" validate constraint "paperclip_ledger_member_id_fkey";

alter table "public"."paperclip_ledger" add constraint "paperclip_ledger_member_milestone_id_fkey" FOREIGN KEY (member_milestone_id) REFERENCES public.member_milestones(id) ON DELETE SET NULL not valid;

alter table "public"."paperclip_ledger" validate constraint "paperclip_ledger_member_milestone_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.apply_reward(p_member uuid, p_rewards jsonb, p_member_milestone bigint)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  v_reward jsonb;
  v_kind   text;
BEGIN
  -- Walk the reward list and dispatch on kind. Each branch resolves its payload
  -- entry as a spec and persists the concrete outcome, so a future randomized
  -- reward computes its value here without any change upstream in record_progress.
  FOR v_reward IN SELECT * FROM jsonb_array_elements(p_rewards)
  LOOP
    v_kind := v_reward ->> 'kind';

    IF v_kind = 'paperclips' THEN
      -- The ledger is the only place a balance lives; this insert is the sole
      -- writer. The resolved amount is what gets stored, never the spec.
      INSERT INTO public.paperclip_ledger (member_id, amount, member_milestone_id)
      VALUES (p_member, (v_reward ->> 'amount')::bigint, p_member_milestone);
    ELSE
      RAISE EXCEPTION 'Unknown reward kind: %', v_kind;
    END IF;
  END LOOP;
END;
$function$
;

-- security_invoker restored by hand: db diff omits view reloptions, so the
-- generated create-or-replace would drop it and the view would read every
-- member's ledger rows instead of running the SELECT policy per-caller.
create or replace view "public"."member_paperclip_balance" with (security_invoker=true) as  SELECT paperclip_ledger.member_id,
    (COALESCE(sum(paperclip_ledger.amount), (0)::numeric))::bigint AS balance
   FROM public.paperclip_ledger
  GROUP BY paperclip_ledger.member_id;


CREATE OR REPLACE FUNCTION public.record_progress(p_member uuid, p_measure text, p_delta bigint)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  v_old bigint;
  v_new bigint;
  v_ms  public.milestones%ROWTYPE;
  v_mm_id bigint;
BEGIN
  -- Ensure the tally row exists, then lock it for the rest of the transaction so
  -- two concurrent sources counting the same measure can't both read the same
  -- `old` and pay a milestone twice.
  INSERT INTO public.member_progress (member_id, measure, tally)
  VALUES (p_member, p_measure, 0)
  ON CONFLICT (member_id, measure) DO NOTHING;

  SELECT tally INTO v_old
    FROM public.member_progress
   WHERE member_id = p_member AND measure = p_measure
     FOR UPDATE;

  v_new := v_old + p_delta;

  UPDATE public.member_progress
     SET tally = v_new, updated_at = now()
   WHERE member_id = p_member AND measure = p_measure;

  -- Milestones whose threshold falls in (old, new] and that this member hasn't
  -- already earned. The half-open interval is the one-shot guard: a later call
  -- that pushes the tally further never re-crosses a threshold already below old.
  FOR v_ms IN
    SELECT m.*
      FROM public.milestones m
     WHERE m.measure = p_measure
       AND m.is_active
       AND m.threshold > v_old
       AND m.threshold <= v_new
       AND NOT EXISTS (
         SELECT 1 FROM public.member_milestones mm
          WHERE mm.member_id = p_member AND mm.milestone_id = m.id
       )
     ORDER BY m.threshold
  LOOP
    -- The unique (member_id, milestone_id) makes the insert the durable one-shot
    -- guard even under a race; DO NOTHING + null RETURNING means a concurrent
    -- winner already paid, so this call skips apply_reward.
    INSERT INTO public.member_milestones (member_id, milestone_id)
    VALUES (p_member, v_ms.id)
    ON CONFLICT (member_id, milestone_id) DO NOTHING
    RETURNING id INTO v_mm_id;

    IF v_mm_id IS NOT NULL THEN
      PERFORM public.apply_reward(p_member, v_ms.rewards, v_mm_id);
    END IF;
  END LOOP;
END;
$function$
;

grant references on table "public"."member_milestones" to "anon";

grant trigger on table "public"."member_milestones" to "anon";

grant truncate on table "public"."member_milestones" to "anon";

grant references on table "public"."member_milestones" to "authenticated";

grant select on table "public"."member_milestones" to "authenticated";

grant trigger on table "public"."member_milestones" to "authenticated";

grant truncate on table "public"."member_milestones" to "authenticated";

grant delete on table "public"."member_milestones" to "service_role";

grant insert on table "public"."member_milestones" to "service_role";

grant references on table "public"."member_milestones" to "service_role";

grant select on table "public"."member_milestones" to "service_role";

grant trigger on table "public"."member_milestones" to "service_role";

grant truncate on table "public"."member_milestones" to "service_role";

grant update on table "public"."member_milestones" to "service_role";

grant references on table "public"."member_progress" to "anon";

grant trigger on table "public"."member_progress" to "anon";

grant truncate on table "public"."member_progress" to "anon";

grant references on table "public"."member_progress" to "authenticated";

grant select on table "public"."member_progress" to "authenticated";

grant trigger on table "public"."member_progress" to "authenticated";

grant truncate on table "public"."member_progress" to "authenticated";

grant delete on table "public"."member_progress" to "service_role";

grant insert on table "public"."member_progress" to "service_role";

grant references on table "public"."member_progress" to "service_role";

grant select on table "public"."member_progress" to "service_role";

grant trigger on table "public"."member_progress" to "service_role";

grant truncate on table "public"."member_progress" to "service_role";

grant update on table "public"."member_progress" to "service_role";

grant references on table "public"."member_unlocks" to "anon";

grant trigger on table "public"."member_unlocks" to "anon";

grant truncate on table "public"."member_unlocks" to "anon";

grant references on table "public"."member_unlocks" to "authenticated";

grant select on table "public"."member_unlocks" to "authenticated";

grant trigger on table "public"."member_unlocks" to "authenticated";

grant truncate on table "public"."member_unlocks" to "authenticated";

grant delete on table "public"."member_unlocks" to "service_role";

grant insert on table "public"."member_unlocks" to "service_role";

grant references on table "public"."member_unlocks" to "service_role";

grant select on table "public"."member_unlocks" to "service_role";

grant trigger on table "public"."member_unlocks" to "service_role";

grant truncate on table "public"."member_unlocks" to "service_role";

grant update on table "public"."member_unlocks" to "service_role";

grant references on table "public"."milestones" to "anon";

grant trigger on table "public"."milestones" to "anon";

grant truncate on table "public"."milestones" to "anon";

grant references on table "public"."milestones" to "authenticated";

grant select on table "public"."milestones" to "authenticated";

grant trigger on table "public"."milestones" to "authenticated";

grant truncate on table "public"."milestones" to "authenticated";

grant delete on table "public"."milestones" to "service_role";

grant insert on table "public"."milestones" to "service_role";

grant references on table "public"."milestones" to "service_role";

grant select on table "public"."milestones" to "service_role";

grant trigger on table "public"."milestones" to "service_role";

grant truncate on table "public"."milestones" to "service_role";

grant update on table "public"."milestones" to "service_role";

grant references on table "public"."paperclip_ledger" to "anon";

grant trigger on table "public"."paperclip_ledger" to "anon";

grant truncate on table "public"."paperclip_ledger" to "anon";

grant references on table "public"."paperclip_ledger" to "authenticated";

grant select on table "public"."paperclip_ledger" to "authenticated";

grant trigger on table "public"."paperclip_ledger" to "authenticated";

grant truncate on table "public"."paperclip_ledger" to "authenticated";

grant delete on table "public"."paperclip_ledger" to "service_role";

grant insert on table "public"."paperclip_ledger" to "service_role";

grant references on table "public"."paperclip_ledger" to "service_role";

grant select on table "public"."paperclip_ledger" to "service_role";

grant trigger on table "public"."paperclip_ledger" to "service_role";

grant truncate on table "public"."paperclip_ledger" to "service_role";

grant update on table "public"."paperclip_ledger" to "service_role";

grant references on table "public"."reward_measures" to "anon";

grant trigger on table "public"."reward_measures" to "anon";

grant truncate on table "public"."reward_measures" to "anon";

grant references on table "public"."reward_measures" to "authenticated";

grant select on table "public"."reward_measures" to "authenticated";

grant trigger on table "public"."reward_measures" to "authenticated";

grant truncate on table "public"."reward_measures" to "authenticated";

grant delete on table "public"."reward_measures" to "service_role";

grant insert on table "public"."reward_measures" to "service_role";

grant references on table "public"."reward_measures" to "service_role";

grant select on table "public"."reward_measures" to "service_role";

grant trigger on table "public"."reward_measures" to "service_role";

grant truncate on table "public"."reward_measures" to "service_role";

grant update on table "public"."reward_measures" to "service_role";


  create policy "members can view their own earned milestones"
  on "public"."member_milestones"
  as permissive
  for select
  to authenticated
using ((( SELECT public.active_member_id() AS active_member_id) = member_id));



  create policy "members can view their own progress"
  on "public"."member_progress"
  as permissive
  for select
  to authenticated
using ((( SELECT public.active_member_id() AS active_member_id) = member_id));



  create policy "members can view their own unlocks"
  on "public"."member_unlocks"
  as permissive
  for select
  to authenticated
using ((( SELECT public.active_member_id() AS active_member_id) = member_id));



  create policy "active milestones readable by authenticated users"
  on "public"."milestones"
  as permissive
  for select
  to authenticated
using ((is_active = true));



  create policy "members can view their own ledger"
  on "public"."paperclip_ledger"
  as permissive
  for select
  to authenticated
using ((( SELECT public.active_member_id() AS active_member_id) = member_id));



  create policy "measures readable by authenticated users"
  on "public"."reward_measures"
  as permissive
  for select
  to authenticated
using (true);


-- Hand-written: db diff emits no function grants, so without these the two
-- internal definer functions land EXECUTE-able by PUBLIC (anon included). They
-- are reusable seams called only from other definer functions, never a client.
revoke all on function public.apply_reward(p_member uuid, p_rewards jsonb, p_member_milestone bigint) from public;
revoke all on function public.apply_reward(p_member uuid, p_rewards jsonb, p_member_milestone bigint) from anon;
revoke all on function public.apply_reward(p_member uuid, p_rewards jsonb, p_member_milestone bigint) from authenticated;
grant all on function public.apply_reward(p_member uuid, p_rewards jsonb, p_member_milestone bigint) to service_role;

revoke all on function public.record_progress(p_member uuid, p_measure text, p_delta bigint) from public;
revoke all on function public.record_progress(p_member uuid, p_measure text, p_delta bigint) from anon;
revoke all on function public.record_progress(p_member uuid, p_measure text, p_delta bigint) from authenticated;
grant all on function public.record_progress(p_member uuid, p_measure text, p_delta bigint) to service_role;



